import { GoTop } from ".";

export default {
  title: 'GoTop',
  component: GoTop,
};

export const Template = () =>{
  return(
    <div>
      <GoTop />
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum consequuntur, molestiae sint magni corrupti aliquid sit excepturi enim nemo dolores qui dolorem. Voluptatum earum nulla, officiis vitae dolores blanditiis velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, commodi dolorum! Ab atque tempore explicabo beatae temporibus quis ea non aliquam ullam veniam animi vero saepe asperiores, officia eveniet illum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente illum laudantium ullam quibusdam voluptatibus mollitia, eveniet enim assumenda molestias neque laboriosam maiores reprehenderit consectetur deleniti aliquid debitis! Ea, laborum repellendus! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci consectetur soluta accusantium vitae voluptate quis doloribus deserunt a facilis vel nobis id dolores asperiores atque rem, assumenda laborum nulla amet. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis maxime sequi ipsa recusandae labore dicta, mollitia reprehenderit doloribus earum dolorem enim consequatur eaque minus aut quisquam omnis, rem, assumenda cumque.</p>

      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum consequuntur, molestiae sint magni corrupti aliquid sit excepturi enim nemo dolores qui dolorem. Voluptatum earum nulla, officiis vitae dolores blanditiis velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, commodi dolorum! Ab atque tempore explicabo beatae temporibus quis ea non aliquam ullam veniam animi vero saepe asperiores, officia eveniet illum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente illum laudantium ullam quibusdam voluptatibus mollitia, eveniet enim assumenda molestias neque laboriosam maiores reprehenderit consectetur deleniti aliquid debitis! Ea, laborum repellendus! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci consectetur soluta accusantium vitae voluptate quis doloribus deserunt a facilis vel nobis id dolores asperiores atque rem, assumenda laborum nulla amet. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis maxime sequi ipsa recusandae labore dicta, mollitia reprehenderit doloribus earum dolorem enim consequatur eaque minus aut quisquam omnis, rem, assumenda cumque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Doloremque quis nihil nam nulla et mollitia eveniet accusamus soluta aspernatur consequuntur quidem fugit voluptatum, error obcaecati quo ad neque commodi ut? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Excepturi quidem aut, rem dicta possimus pariatur dolores tempora asperiores magni recusandae sit delectus ab voluptatum enim suscipit assumenda placeat esse. Laboriosam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum in maxime asperiores quia veritatis labore iste architecto. Amet repudiandae quae incidunt perspiciatis! Deserunt, temporibus aliquid. Tempora eaque impedit sint odit! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugiat eius aliquam aperiam magni nisi veritatis cum doloribus harum, quae sit assumenda, explicabo ea vel consequuntur iste eos eligendi? Officia, architecto. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla unde pariatur distinctio perferendis autem repellat veritatis illo totam non sunt, fugit quam quaerat aspernatur nesciunt reprehenderit delectus eum adipisci quia! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab numquam deserunt velit dolorem, excepturi placeat ea voluptate iste quaerat perferendis repudiandae rerum odio incidunt ipsum quisquam officiis vitae sint dolore.</p>

      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum consequuntur, molestiae sint magni corrupti aliquid sit excepturi enim nemo dolores qui dolorem. Voluptatum earum nulla, officiis vitae dolores blanditiis velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, commodi dolorum! Ab atque tempore explicabo beatae temporibus quis ea non aliquam ullam veniam animi vero saepe asperiores, officia eveniet illum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente illum laudantium ullam quibusdam voluptatibus mollitia, eveniet enim assumenda molestias neque laboriosam maiores reprehenderit consectetur deleniti aliquid debitis! Ea, laborum repellendus! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci consectetur soluta accusantium vitae voluptate quis doloribus deserunt a facilis vel nobis id dolores asperiores atque rem, assumenda laborum nulla amet. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis maxime sequi ipsa recusandae labore dicta, mollitia reprehenderit doloribus earum dolorem enim consequatur eaque minus aut quisquam omnis, rem, assumenda cumque.</p>

      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum consequuntur, molestiae sint magni corrupti aliquid sit excepturi enim nemo dolores qui dolorem. Voluptatum earum nulla, officiis vitae dolores blanditiis velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, commodi dolorum! Ab atque tempore explicabo beatae temporibus quis ea non aliquam ullam veniam animi vero saepe asperiores, officia eveniet illum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente illum laudantium ullam quibusdam voluptatibus mollitia, eveniet enim assumenda molestias neque laboriosam maiores reprehenderit consectetur deleniti aliquid debitis! Ea, laborum repellendus! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci consectetur soluta accusantium vitae voluptate quis doloribus deserunt a facilis vel nobis id dolores asperiores atque rem, assumenda laborum nulla amet. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis maxime sequi ipsa recusandae labore dicta, mollitia reprehenderit doloribus earum dolorem enim consequatur eaque minus aut quisquam omnis, rem, assumenda cumque.</p>

      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum consequuntur, molestiae sint magni corrupti aliquid sit excepturi enim nemo dolores qui dolorem. Voluptatum earum nulla, officiis vitae dolores blanditiis velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, commodi dolorum! Ab atque tempore explicabo beatae temporibus quis ea non aliquam ullam veniam animi vero saepe asperiores, officia eveniet illum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente illum laudantium ullam quibusdam voluptatibus mollitia, eveniet enim assumenda molestias neque laboriosam maiores reprehenderit consectetur deleniti aliquid debitis! Ea, laborum repellendus! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci consectetur soluta accusantium vitae voluptate quis doloribus deserunt a facilis vel nobis id dolores asperiores atque rem, assumenda laborum nulla amet. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis maxime sequi ipsa recusandae labore dicta, mollitia reprehenderit doloribus earum dolorem enim consequatur eaque minus aut quisquam omnis, rem, assumenda cumque.</p>

      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum consequuntur, molestiae sint magni corrupti aliquid sit excepturi enim nemo dolores qui dolorem. Voluptatum earum nulla, officiis vitae dolores blanditiis velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, commodi dolorum! Ab atque tempore explicabo beatae temporibus quis ea non aliquam ullam veniam animi vero saepe asperiores, officia eveniet illum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente illum laudantium ullam quibusdam voluptatibus mollitia, eveniet enim assumenda molestias neque laboriosam maiores reprehenderit consectetur deleniti aliquid debitis! Ea, laborum repellendus! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci consectetur soluta accusantium vitae voluptate quis doloribus deserunt a facilis vel nobis id dolores asperiores atque rem, assumenda laborum nulla amet. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis maxime sequi ipsa recusandae labore dicta, mollitia reprehenderit doloribus earum dolorem enim consequatur eaque minus aut quisquam omnis, rem, assumenda cumque.</p>

      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum consequuntur, molestiae sint magni corrupti aliquid sit excepturi enim nemo dolores qui dolorem. Voluptatum earum nulla, officiis vitae dolores blanditiis velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, commodi dolorum! Ab atque tempore explicabo beatae temporibus quis ea non aliquam ullam veniam animi vero saepe asperiores, officia eveniet illum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente illum laudantium ullam quibusdam voluptatibus mollitia, eveniet enim assumenda molestias neque laboriosam maiores reprehenderit consectetur deleniti aliquid debitis! Ea, laborum repellendus! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci consectetur soluta accusantium vitae voluptate quis doloribus deserunt a facilis vel nobis id dolores asperiores atque rem, assumenda laborum nulla amet. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis maxime sequi ipsa recusandae labore dicta, mollitia reprehenderit doloribus earum dolorem enim consequatur eaque minus aut quisquam omnis, rem, assumenda cumque.</p>

      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum consequuntur, molestiae sint magni corrupti aliquid sit excepturi enim nemo dolores qui dolorem. Voluptatum earum nulla, officiis vitae dolores blanditiis velit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, commodi dolorum! Ab atque tempore explicabo beatae temporibus quis ea non aliquam ullam veniam animi vero saepe asperiores, officia eveniet illum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente illum laudantium ullam quibusdam voluptatibus mollitia, eveniet enim assumenda molestias neque laboriosam maiores reprehenderit consectetur deleniti aliquid debitis! Ea, laborum repellendus! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci consectetur soluta accusantium vitae voluptate quis doloribus deserunt a facilis vel nobis id dolores asperiores atque rem, assumenda laborum nulla amet. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis maxime sequi ipsa recusandae labore dicta, mollitia reprehenderit doloribus earum dolorem enim consequatur eaque minus aut quisquam omnis, rem, assumenda cumque.</p>

    </div>
  );
};
